name: Lint & Compile test code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  lint-compile:
    uses: Hazmi35/workflows/.github/workflows/pnpm-eslint-typescript.yaml@646ebf53969f65417daa2677643d4c7b4cbe9fa9 # master
    secrets: inherit
