name: Release package to NPM & GitHub registry

on:
  release:
    types: [created]

jobs:
  publish:
    uses: Hazmi35/workflows/.github/workflows/pnpm-publish-typescript.yml@master
    secrets: inherit
